### ISSUE TITLE
Ability to disable auto-complete functionality.

### ISSUE THREAD

**Issue by imsofi** [dbcli/litecli#105]
I like what this command line program does, but i dont like using auto-complete functionality. But i cant find a way to turn it off with the config file. Also the docs only mentions "Auto-completion is on by default" with no mention how to turn this feature off.

**Comment by amjith** [comment]
@imsofi There is no way to turn off the autocompletion. I'm not sure what value we will add to the default sqlite shell if you turn off auto-completion. Unless I misunderstood your question.

**Comment by imsofi** [comment]
Well it would work in the similar way to how ipython is to python. It gives me the inline syntax highlighting, the emacs keybinds and tab completion. But doesnt get in the way of me writing the actual lines. Something the auto complete of litecli sadly does for me. And id like to disable it/hide it until i click tab.

**Comment by amjith** [comment]
@imsofi I have created a new PR to address this request. Can you give it a try? 

You can install it from a branch using the following command: 

```
pip install -U https://github.com/dbcli/litecli/archive/refs/heads/autocomplete-optional.zip
```

You can then add a new line in your [config file](https://github.com/dbcli/litecli/blob/974d061627bb9ab371d6d0b8348b59543110f184/litecli/liteclirc#L57) (located at ~/.config/litecli/config) with the following contents: 

```
autocompletion = False 
```

**Comment by imsofi** [comment]
Seems to work well, thanks!
