### ISSUE TITLE
History and Log Storage Location

### ISSUE THREAD

**Issue by theduke** [dbcli/litecli#111]
On Linux the history and log are stored in `~/.config/litecli`, which is not ideal since this directory should only contain config files.

Storing them in `~/.local/share/litecli` would be more sensible and conform to the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by amjith** [comment]
This is unlikely to change. 

I know this is a lame reason but it introduces additional complexity to the code base and we're not the only one who does this (eg: Chrome).
