### ISSUE TITLE
.read does nothing

### ISSUE THREAD

**Issue by dflaxx** [dbcli/litecli#120]
`.read <filename.sql>` does not seem to work properly. When executing a query from an sql file using `.read` on an existing database, there is no output. Instead, only the execution time is printed. When doing the same thing in interactive SQLite, the query is executed and there is output.

Could you please clarify if this is a bug, a missing feature or an error on my side?

Thanks and best regards!

**Comment by zzl0** [comment]
@dflaxx thanks for reporting this issue. I have reproduced this on my side as well. It's a bug in `litecli`, the official `sqlite3` doesn't have this issue.

```sql
$ sqlite3 ex1
SQLite version 3.32.3 2020-06-18 14:16:19
Enter ".help" for usage hints.
sqlite> .read myscript.sql
hello!|10
goodbye|20

$ litecli ex1
Version: 1.6.0
Mail: https://groups.google.com/forum/#!forum/litecli-users
GitHub: https://github.com/dbcli/litecli
ex1> .read myscript.sql
Time: 0.001s
```
