### ISSUE TITLE
use \033 in prompt

### ISSUE THREAD

**Issue by one-pyy** [dbcli/litecli#135]
In mycli:
![image](https://user-images.githubusercontent.com/72590023/164576953-098304e9-0a39-4cf3-b01b-1accbb5f83f0.png)
In litecli:
![image](https://user-images.githubusercontent.com/72590023/164576982-626815ed-fa64-45f6-9b5d-ca3180710e80.png)

**Comment by amjith** [comment]
@one-pyy If you're feeling generous this could be an opportunity to contribute some code and make litecli feature compatible with mycli. 

Looks like you just need to run the prompt string through the ANSI() function that comes built in with prompt-toolkit. 

Here's how this is implemented in mycli: https://github.com/dbcli/mycli/blob/main/mycli/main.py#L617

You might want to open a PR for litecli that implements this feature. :)

**Comment by one-pyy** [comment]
Thank you very much for your reply

**Comment by one-pyy** [comment]
I'm very sorry, I tried to change the source code, then it reported an error and I couldn't find a way to fix it. So I may not be able to contribute some code (ノへ￣、)

**Comment by one-pyy** [comment]
![image](https://user-images.githubusercontent.com/72590023/165882355-0c19ffd0-d0ca-4f59-a49d-5274ba2f3aa7.png)
Thank you very much for your help, it works!
♪(･ω･)
