### ISSUE TITLE
Feature request for `.indexes` command support.

### ISSUE THREAD

**Issue by zxymike93** [dbcli/litecli#138]

**Comment by amjith** [comment]
@zxymike93 I have implemented this in a PR. Can you please verify that it works as expected? 

You can install directly from this branch using the following command: 

```
pip install -U https://github.com/dbcli/litecli/archive/refs/heads/add-indexes.zip
```

**Comment by amjith** [comment]
Released a new version. Please upgrade to get the new `.indexes` command. 

```
pip install -U litecli
```
