### ISSUE TITLE
Header names vague or hidden in grid mode

### ISSUE THREAD

**Issue by MohamSayed** [dbcli/litecli#154]
Header names vague or hidden in grid mode. I don't think it is good idea to highlight names in header.
![image](https://user-images.githubusercontent.com/26751824/226489513-9ca288c6-5f3d-4bcc-9541-231edb03e1ee.png)
![image](https://user-images.githubusercontent.com/26751824/226489677-29218641-6120-4dd4-b899-baac2c222f0c.png)

OS: Windows 11
Python: 3.9.16
Terminal: Microsoft Terminal
Shell: Powershell

**Comment by amjith** [comment]
@MohamSayed Sorry about the awful highlights of the header. Fortunately this is an easy fix. You can open your config located in `~/.config/litecli/config` and edit the line towards the bottom that says `output.header = "#00ff5f bold"` and set it to `output.header = ""` 

That should get rid of the header highlights. 

I don't remember where the config file is located in Windows. I hope you can find it.

**Comment by MohamSayed** [comment]
Config location: ~\AppData\Local\dbcli\litecli\config
