### ISSUE TITLE
syntax style changes output behaviour

### ISSUE THREAD

**Issue by exastone** [dbcli/litecli#169]
Tested on WezTerm and Windows Terminal.

Changing `syntax_style = default` in the config to any of the following (there may be others, these are just the ones I tried):

- `syntax_style = xcode-dark`
- `syntax_style = igor-dark`
- `syntax_style = fruity`
- `syntax_style = fruity-dark`

I checked the non-dark variants of these and the following do **not** have the same issue as their dark counterpart.
- `syntax_style = xcode`
- `syntax_style = igor`

**Expected Behavior;** (exhibited with syntax_style set to default, xcode, igor, others I didn't try?)

<img width="359" alt="image" src="https://github.com/dbcli/litecli/assets/61954919/9b2a3936-d235-416a-accf-e7cd6cbbf530">

**Actual Behavior:**
Output is directed to some temp buffer (reminds me of pager buffer?) instead of to the running litecli instance

<img width="440" alt="image" src="https://github.com/dbcli/litecli/assets/61954919/c68b4cc4-9e51-4073-a8d3-9f26ff0268ab">

Notice the below image is the contents of terminal after pressing 'q' to leave the temp buffer shown above.

<img width="364" alt="image" src="https://github.com/dbcli/litecli/assets/61954919/e8115ecb-16fc-445b-a1ac-5f8156d2c224">

**Comment by amjith** [comment]
I'm not able to reproduce this. I'm guessing this has something to do with your terminal's color scheme clashing with the litecli colorscheme.

I'd recommend changing the terminal scheme or try a different terminal and reopen the issue if it still persists.
