### ISSUE TITLE
The describe command fails with 'near "(": syntax error'

### ISSUE THREAD

**Issue by sterat** [dbcli/litecli#190]
Any use of the describe command results in a syntax error.

```
dev.db> \d auth_user
near "(": syntax error
```

This is due to passing a tuple to `format()` instead of the string arg directly.

```
    if arg:
        args = (arg,)
        query = """
            PRAGMA table_info({})
        """.format(args)  # <-- this should just be arg, as it was in the previous commit
    else:
        return list_tables(cur)
```

**Comment by amjith** [comment]
Sorry about that. I've opened a new PR (#191) to fix it. Can you give it a shot by installing it from the branch? 

```
pip install -U https://github.com/dbcli/litecli/archive/refs/heads/fix-special-cmd-d.zip
```

I'm glad to see someone else using the `\d table` to describe the tables. I thought I was the only one who knew about it. 😄

**Comment by sterat** [comment]
Yes I can confirm that fixes it, thanks!
