### ISSUE TITLE
Arch AUR distribution

### ISSUE THREAD

**Issue by randrej** [dbcli/litecli#34]
I've added both the current master and the latest tag versions of this program to Arch Linux's user repository (AUR). You may add that to the Installation section of the readme.

The packages are:
https://aur.archlinux.org/packages/litecli/
and
https://aur.archlinux.org/packages/litecli-git/

Specifying a command to install AUR packages is kind of a taboo in Arch circles. The general wisdom is to `git clone` the package off of AUR and then `makepkg` it yourself, but there are so-called *AUR-helpers* that automate the process, provide easy updates and so on. One of them is `yay`, but adding that might enrage some purists and they may say you're pushing `yay` on them (when there are other helpers and the manual method).

To install the packages with yay, you'd write:

    yay -S litecli
or

    yay -S litecli-git

**Comment by amjith** [comment]
I am flattered. Would you mind sending a PR to the README?

**Comment by amjith** [comment]
When we release a new version will you be updating the Arch package? I don't run Arch to do this myself, so I'll have to rely on you.

**Comment by randrej** [comment]
Sure, I sent a PR for the file: #35 

Yes, I will be updating the `litecli` package whenever you push a tag here, it's on my watchlist.

`litecli-git` is built from the git master branch and the package isn't updated unless something in the build process changes (or you add/remove a dependency). I'll handle that, too.

**Comment by randrej** [comment]
I've used two of your packages (pgcli and mycli) for a year or two, and I was looking at the same thing for sqlite. Couldn't find anything on duckduckgo, came to github to look at how you implemented mycli and pgcli and found this among the projects in the dbcli account.

I've been using it for a week or so, so far it works very well (and pretty much the same way as pgcli and mycli).

I have found one bug so far (I'll add it as a separate issue if you want): 

When using Vi mode + multiline, write any amount of code and exit the insert mode into normal mode.  
Let's say I wrote this:

```sql
SELECT 1 AS x, 2 AS y;
```
Now, you can move the cursor anywhere, reenter insert mode by using i and press enter and the command is submitted, which is unwanted behavior. I think that pressing enter in insert mode should just add a newline, except if it's pressed after the last ; at the end of query. Pressing enter in normal mode should always submit the command, as it does now.

**Comment by amjith** [comment]
What you've described is a new feature request. I wouldn't call that a bug. 

As soon as your add a semi-colon to the end of the line, we will submit the query to the database on enter. If you would like to continue to add newlines, I'd recommend not adding the semi-colon at the end and only add the semi-colon when the query is ready to be submitted.

**Comment by randrej** [comment]
Thanks for the info! If I leave out the semicolon at the end, everything works fine.
