### ISSUE TITLE
Install on mac OS X / anaconda fails

### ISSUE THREAD

**Issue by the-holger** [dbcli/litecli#36]
Hi! I'm trying to install litecli via pip on my mac OS X (10.14.3) MBP with Miniconda 4 (Python 3.7.0).
The install fails with `error: can't copy 'doc/lightcli.3': doesn't exist or not a regular file`

Any idea how I can fix that?

**Comment by amjith** [comment]
Looks like you're trying to install `lightcli` which is not this project. 

This project is called `litecli`. The spelling is different.
