### ISSUE TITLE
Unusable on dark background

### ISSUE THREAD

**Issue by jbulow** [dbcli/litecli#40]
Some text is written with same color as background. No documentation on how to change/use themes other than "edit config file".

**Comment by amjith** [comment]
https://litecli.com/config/ had instructions on the location of your config file.

Look for "syntax_style" in that file. 

Here's a gallery of all the themes:

https://litecli.com/syntax/

You can click on an image to see it on dark background.

**Comment by jbulow** [comment]
Thanks!

I missed it in the config file as I searched for "theme". Maybe mention the config option to use on the [theme page](https://litecli.com/syntax/) ?

**Comment by amjith** [comment]
Fair point. I have updated the page. 

I appreciate your feedback. :smile:
