### ISSUE TITLE
Suggestion: shift+tab to start completion in the opposite direction

### ISSUE THREAD

**Issue by elig0n** [dbcli/litecli#57]
Right now one has to hit "tab" first and then "shift+tab" to go to opposite direction.

**Comment by amjith** [comment]
Yup. This is possible. I'll take a look at it.

**Comment by amjith** [comment]
@elig0n Can you try installing from master? We have this implemented now. 

Command to install from master:

`pip install -U https://github.com/dbcli/litecli/archive/master.zip`

**Comment by elig0n** [comment]
Thank you very much

**Comment by amjith** [comment]
This is now released as v.1.10

Please upgrade to get this feature. `pip install -U litecli`
