### ISSUE TITLE
multi line commands?

### ISSUE THREAD

**Issue by godfrey-cw** [dbcli/litecli#60]
In the regular `sqlite3` shell, since commands need to end with a semi-colon one can use multiline commands (by not ending a line with a semicolon).

Unless I'm mistaken that's not the case with the `litecli`, e.g. this command works:
```
ex1> select * from tbl1 where two = 10                                                                                      
+--------+-----+
| one    | two |
+--------+-----+
| hello! | 10  |
+--------+-----+
1 row in set
Time: 0.020s
```
even though I forgot the ";", but this command fails 
```
ex2> create table tbl3 (g1 varchar(30) primary key,                                                                         
incomplete input
```
since I pressed enter before finishing the table.

Is there an alternative way to do multiline commands?

**Comment by amjith** [comment]
Yes. If you press F3 you'll be switched to multi line mode. Then you'll
need a semi colon to end a statement.

You can make this your default by editing the config file located at
~/.config/litecli/config.

**Comment by godfrey-cw** [comment]
Wonderful, many thanks for your quick reply! And I literally just found that at the top of the sample config, sorry for not spending a couple minutes with the documentation before posting an issue. Thanks for the great cli!
