### ISSUE TITLE
Snap [Feature Request]

### ISSUE THREAD

**Issue by mikeroyal** [dbcli/litecli#74]
I was wondering if you might have an interest in a [snap](https://snapcraft.io/) version. I would help make the snap and submit a PR if there's any interest now or in the furture.
[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

**Comment by amjith** [comment]
@mikeroyal If you'd like to create and maintain a snap package for litecli, I'd welcome that. My concern is keeping it up to date. We've tried creating deb packages in the past and it is a pain to update it for every release. So I've decided to let someone else create binary packages such snap, deb, rpm etc.
