### ISSUE TITLE
[question] Integration Instructions

### ISSUE THREAD

**Issue by leonjza** [dbcli/litecli#75]
First of all, thanks for this awesome project!

I have a case where I integrated litecli [here](https://github.com/sensepost/objection/blob/a5475828652f6058e2fc58ef5e8d628715109e75/objection/commands/sqlite.py#L90-L93). Based on how configuration parsing works in litecli and the fact that I wanted to change some defaults, I am currently monkey patching the lib [here](https://github.com/sensepost/objection/blob/a5475828652f6058e2fc58ef5e8d628715109e75/objection/commands/sqlite.py#L12-L29) to modify default values. My primary concern is obviously the longevity of this probably unsupported and hacky method of using the library.

Is there any integration documentation that I may have missed, or alternative suggestions to better integrate. I am totally ok with "not right now" as an answer ofc.

Thanks!

**Comment by amjith** [comment]
That's pretty awesome! 

We hadn't given a lot of thought into integration or using litecli as a library. Sorry about having to monkey patch things. 

Could you ship your own config file? We do take an argument to LiteCli() class called `liteclirc` which is a path to a config file. Would that work?

**Comment by leonjza** [comment]
I could definitely do that yeah. I figured for just the two options that I am flipping that may not be necessary, but it probably makes more sense in the long run in case config handing changes internally.

Thanks for the response!
