### ISSUE TITLE
prompt-toolkit-upgrade

### ISSUE THREAD

**Issue by leonjza** [dbcli/litecli#83]
We use litecli as detailed in #75. `python-prompt-toolkit` has reached version 3, but litecli requires version 2 still. Any chance for an upgrade, please? The upgrade itself should be pretty simple as detailed [here](https://python-prompt-toolkit.readthedocs.io/en/master/pages/upgrading/3.0.html).

```
ERROR: litecli 1.2.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 3.0.3 which is incompatible.
```

**Comment by leonjza** [comment]
Bump.

**Comment by amjith** [comment]
@leonjza I'm happy to take a PR if you can. 

I'm swamped at work and have low bandwidth at the moment to do the due testing to make sure the upgrade won't break everything. :smile:

**Comment by leonjza** [comment]
I made PR #84 for this.

**Comment by amjith** [comment]
Merged and released a new version of litecli.
